-- Insert governance prompts (table was empty because columns were missing during seed)
INSERT INTO governance_prompts (name, category, content, criticality, status, description, is_generic, related_files, related_tables, related_functions) VALUES
('Proteção contra Escalação de Privilégios', 'Segurança', 'NUNCA armazene roles/permissões na tabela de perfis ou users. Roles DEVEM estar em uma tabela separada (user_roles) com RLS habilitado. NUNCA verifique status de admin via localStorage, sessionStorage ou credenciais hardcoded. Sempre use validação server-side com SECURITY DEFINER functions.', 'high', 'implemented', 'Regras para prevenir escalação de privilégios administrativos.', false, ARRAY['src/hooks/useAuth.tsx','src/hooks/usePlatformAdmin.ts'], ARRAY['user_roles','profiles'], ARRAY['has_role','is_platform_admin']),
('Proteção de Edge Functions', 'Backend', 'Toda edge function que modifique dados DEVE: 1) Validar token via supabase.auth.getUser(token). 2) Verificar permissões na tabela user_roles. 3) NUNCA confiar em dados do cliente. 4) Usar SUPABASE_SERVICE_ROLE_KEY apenas no servidor.', 'high', 'implemented', 'Regras obrigatórias para segurança de Edge Functions.', false, ARRAY['supabase/functions/'], ARRAY['user_roles'], ARRAY['verifyAdmin']),
('Row Level Security (RLS)', 'Segurança', 'TODAS as tabelas com dados de usuário DEVEM ter RLS habilitado. Use funções SECURITY DEFINER para evitar recursão em policies. Nunca desabilite RLS "temporariamente".', 'high', 'implemented', 'Padrões obrigatórios de RLS para todas as tabelas.', false, NULL, ARRAY['todas as tabelas públicas'], ARRAY['get_user_org_id','has_role']),
('Proteção contra Manipulação de Banco', 'Segurança', 'NUNCA permita que o cliente envie SQL raw. Sempre filtre por auth.uid() ou team_id validado. Inputs validados com zod. Limite campos atualizáveis.', 'high', 'implemented', 'Regras contra manipulação direta de dados.', false, NULL, ARRAY['todas as tabelas públicas'], NULL),
('Proteção de Webhooks e APIs Públicas', 'Backend', 'Webhooks públicos DEVEM usar tokens únicos para autenticação. Valide e sanitize TODOS os dados recebidos. Rate limiting deve ser implementado.', 'high', 'implemented', 'Segurança para endpoints públicos e webhooks.', false, ARRAY['supabase/functions/zapi-webhook/index.ts','supabase/functions/widget-submit/index.ts'], NULL, NULL),
('Proteção de Secrets e API Keys', 'Infraestrutura', 'NUNCA armazene chaves privadas no código-fonte. Use variáveis de ambiente/secrets do servidor. Service Role Keys NUNCA devem ser expostas ao cliente.', 'high', 'implemented', 'Gerenciamento seguro de chaves e secrets.', false, ARRAY['.env','supabase/functions/'], NULL, NULL),
('Prompt Completo para Outra Ferramenta', 'Governança', 'REGRAS DE SEGURANÇA OBRIGATÓRIAS:\n- Roles em tabela separada (user_roles)\n- RLS em TODAS as tabelas\n- Verificação server-side em TODA edge function\n- Validação de input com zod\n- Service Role Key apenas no servidor\n- NUNCA usar localStorage para verificar admin\n- Sanitizar HTML antes de renderizar', 'high', 'implemented', 'Prompt master com todas as regras de segurança para uso em qualquer ferramenta de IA.', false, NULL, NULL, NULL),
-- Generic library prompts
('Roubo de Tokens de Acesso', 'Segurança', 'Token de projeto rotativo a cada 15 minutos. Mitigação: rotação automática, validação server-side, monitoramento de uso anômalo.', 'high', 'documented', 'Ameaça real: reutilização de token de projeto.', true, NULL, NULL, NULL),
('Bloqueio e Manipulação de Conteúdo', 'Segurança', 'Utiliza-se event socket para manipular conteúdos. Mitigação: validação server-side de todas as rotas, assinatura de requests.', 'high', 'documented', 'Ameaça real: manipulação via event socket.', true, NULL, NULL, NULL),
('Rastreamento e Exfiltração de Dados', 'Segurança', 'Código de HWID para evitar que 1 licença seja usada para múltiplas pessoas. Mitigação: fingerprinting, limite de sessões.', 'high', 'documented', 'Ameaça real: uso de HWID para controle de licenças.', true, NULL, NULL, NULL),
('Ofuscação Extrema de Código', 'Infraestrutura', 'Ofuscação para evitar vazamento das chaves Supabase. Mitigação: nunca expor service role key, usar apenas anon key no client.', 'high', 'documented', 'Ameaça real: proteção contra vazamento de chaves Supabase.', true, NULL, NULL, NULL);