// Flow Builder Types

export type FlowNodeType =
  | 'start'
  | 'content-block'
  | 'message-buttons'
  | 'message-list'
  | 'action-tag'
  | 'action-pipeline'
  | 'action-transfer'
  | 'action-webhook'
  | 'action-flow'
  | 'action-department'
  | 'action-document'
  | 'action-delay'
  | 'action-workspace'
  | 'action-contact-field'
  | 'action-whatsapp-group'
  | 'condition'
  | 'user-input'
  | 'ai-handoff'
  | 'ai-return'
  | 'randomizer'
  | 'smart-delay';

// === SALVAR NO CONTATO ===

/**
 * Uma gravacao do no 'action-contact-field': manda o valor (texto livre, com
 * {{variavel}}) para uma chave de contact_custom_fields, que o motor persiste em
 * contacts.metadata.custom_fields.
 */
export interface ContactFieldAssignment {
  id: string;
  /** key de contact_custom_fields. E tambem o nome da variavel {{key}}. */
  fieldKey: string;
  /** Valor a gravar. Passa por replaceVariables antes de ir pro banco. */
  value: string;
}

// Content Block Item Types
export type ContentItemType = 'text' | 'image' | 'video' | 'audio' | 'document' | 'delay';

export interface ContentItem {
  id: string;
  type: ContentItemType;
  content?: string;
  mediaUrl?: string;
  caption?: string;
  saveTranscription?: boolean;
  transcription?: string;
  delaySeconds?: number;
}

export interface ContentBlockConfig {
  items: ContentItem[];
}

// === REMARKETING STEP TYPES ===

export interface RemarketingStep {
  id: string;
  delayMinutes: number;    // 4.55, 10, 30, 60, 1440, etc.
  message: string;         // Generated by AI or manual
}

export const REMARKETING_DELAY_PRESETS = [
  { label: '4m33s', minutes: 4.55 },
  { label: '10min', minutes: 10 },
  { label: '30min', minutes: 30 },
  { label: '1h', minutes: 60 },
  { label: '2h', minutes: 120 },
  { label: '1 dia', minutes: 1440 },
  { label: '3 dias', minutes: 4320 },
  { label: '5 dias', minutes: 7200 },
  { label: '10 dias', minutes: 14400 },
];

export interface FlowNodeData {
  label: string;
  type: FlowNodeType;
  config?: Record<string, unknown>;
}

// === CONDITION RULE TYPES ===

export type ConditionRuleType =
  | 'tag'
  | 'pipeline'
  | 'assigned'
  | 'variable'
  | 'contact_field'
  | 'service_mode';

export type ConditionOperator =
  | 'equals'
  | 'not_equals'
  | 'contains'
  | 'not_contains'
  | 'greater_than'
  | 'less_than'
  | 'exists'
  | 'not_exists';

export interface ConditionRule {
  id: string;
  type: ConditionRuleType;
  negate?: boolean;
  // For tag
  tagId?: string;
  // For pipeline
  pipelineId?: string;
  columnId?: string;
  // For assigned
  userId?: string;
  // For variable
  variable?: string;
  operator?: ConditionOperator;
  value?: string;
  // For contact_field
  contactField?: 'name' | 'email' | 'phone';
  // For service_mode
  serviceMode?: 'pending' | 'bot' | 'human';
}

export interface AdvancedConditionConfig {
  matchType: 'all' | 'any';
  rules: ConditionRule[];
}

// === RANDOMIZER TYPES ===

export interface RandomizerVariant {
  id: string;
  label: string;
  weight: number;
}

export interface RandomizerConfig {
  variants: RandomizerVariant[];
}

// === SMART DELAY TYPES ===

export type SmartDelayType = 'fixed' | 'until_time' | 'until_business_hours' | 'until_date';

export interface SmartDelayConfig {
  delayType: SmartDelayType;
  fixedMinutes?: number;
  time?: string;
  businessHoursStart?: string;
  businessHoursEnd?: string;
  weekdaysOnly?: boolean;
  date?: string;
}

// Message Node Configs
export interface TextMessageConfig {
  content: string;
  formatting?: {
    bold?: boolean;
    italic?: boolean;
  };
}

export interface MediaMessageConfig {
  mediaType: 'image' | 'video' | 'audio' | 'document';
  mediaUrl?: string;
  caption?: string;
}

export interface ButtonsMessageConfig {
  text: string;
  /** Título em negrito acima da mensagem (nativo na Evolution). */
  title?: string;
  /** Rodapé abaixo dos botões (nativo na Evolution). */
  footer?: string;
  buttons: Array<{
    id: string;
    label: string;
  }>;
}

export interface ListMessageConfig {
  headerText: string;
  bodyText: string;
  buttonText: string;
  sections: Array<{
    title: string;
    items: Array<{
      id: string;
      title: string;
      description?: string;
    }>;
  }>;
}

// Action Node Configs
export interface WhatsAppGroupActionConfig {
  groupId: string;
  groupJid: string;
  groupName?: string;
  items: ContentItem[];
}

export interface TagActionConfig {
  action: 'add' | 'remove';
  tagId: string;
}

export interface PipelineActionConfig {
  pipelineColumnId: string;
  /**
   * 'move' (padrao) tira o card do funil de origem; 'add' inscreve a conversa
   * neste funil sem tirar dos outros — e assim que nasce o "funil por evento".
   */
  pipelineAction?: 'move' | 'add';
}

export interface TransferActionConfig {
  agentType: 'human' | 'ai';
  agentId: string;
  /**
   * Encerra a IA de vez: limpa o agente da conversa e grava
   * ai_paused_until='permanent'. Sem isto, transferir para humano só troca o
   * service_mode e um master prompt por keyword reassume a conversa depois.
   */
  stopAI?: boolean;
}

export interface DelayActionConfig {
  duration: number;
  unit: 'seconds' | 'minutes' | 'hours';
}

export interface WebhookActionConfig {
  url: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  headers?: Record<string, string>;
  body?: string;
}

// Legacy - kept for backward compat
export interface ConditionConfig {
  variable: string;
  operator: 'equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than';
  value: string;
}

export interface UserInputConfig {
  variableName: string;
  inputType: 'text' | 'number' | 'email' | 'phone' | 'cpf';
  validationMessage?: string;
}

// AI Node Configs
export interface AIHandoffConfig {
  agentId?: string;
  contextMessage?: string;
}

/**
 * O nó 'ai-return' não tem configuração: ele encerra o handoff e o fluxo segue
 * pela aresta de saída. (Havia um `returnToNodeId` aqui que nunca teve
 * implementação — o roteamento sempre foi pela aresta.)
 */
export type AIReturnConfig = Record<string, never>;

// Sidebar Component Categories
export interface FlowComponentCategory {
  id: string;
  label: string;
  icon: string;
  components: FlowComponent[];
}

export interface FlowComponent {
  type: FlowNodeType;
  label: string;
  description: string;
  icon: string;
  color: string;
}
