// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rifpapkaqjnjvuadzilw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZnBhcGthcWpuanZ1YWR6aWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNDgwMTAsImV4cCI6MjA4NzYyNDAxMH0.ocRO9PihzBATGqc4Rkbdb5y8_Z80iEJMMbUIWZFBbLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});